import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import aiRouter from "./ai.js";
import generalRouter from "./general.js";
import organizationsRouter from "./organizations.js";
import usersRouter from "./users.js";
import projectsRouter from "./projects.js";
import documentsRouter from "./documents.js";
import correspondenceRouter from "./correspondence.js";
import workflowsRouter from "./workflows.js";
import tasksRouter from "./tasks.js";
import metadataRouter from "./metadata.js";
import dashboardRouter from "./dashboard.js";
import searchRouter from "./search.js";
import auditLogsRouter from "./audit-logs.js";
import packagesRouter from "./packages.js";
import transmittalsRouter from "./transmittals.js";
import notificationsRouter from "./notifications.js";
import configRouter from "./config.js";
import storageRouter from "./storage.js";
import adminRouter from "./admin.js";
import publicShareRouter from "./public-share.js";
import globalDocumentsRouter from "./global-documents.js";
import registersRouter from "./registers.js";
import deliverablesRouter from "./deliverables.js";
import preferencesRouter from "./preferences.js";
import notificationSummaryRouter from "./notification-summary.js";
import modulesRouter from "./modules.js";
import profileRouter from "./profile.js";
import meetingsRouter from "./meetings.js";
import chatRouter from "./chat.js";
import devRouter from "./dev.js";
import calendarRouter from "./calendar.js";
import rulesRouter from "./rules.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/organizations", organizationsRouter);
router.use("/users", usersRouter);
router.use("/projects", projectsRouter);
router.use("/projects/:projectId/documents", documentsRouter);
router.use("/projects/:projectId/correspondence", correspondenceRouter);
router.use("/projects/:projectId/workflows", workflowsRouter);
router.use("/projects/:projectId/packages", packagesRouter);
router.use("/projects/:projectId/transmittals", transmittalsRouter);
router.use("/tasks", tasksRouter);
router.use("/metadata-fields", metadataRouter);
router.use("/dashboard", dashboardRouter);
router.use("/search", searchRouter);
router.use("/audit-logs", auditLogsRouter);
router.use("/ai", aiRouter);
router.use("/general", generalRouter);
router.use("/notifications", notificationsRouter);
router.use("/config", configRouter);
router.use("/storage", storageRouter);
router.use("/admin", adminRouter);
router.use("/public/share", publicShareRouter);
router.use("/documents", globalDocumentsRouter);
router.use("/projects/:projectId", registersRouter);
router.use("/projects/:projectId", deliverablesRouter);
router.use("/user", preferencesRouter);
router.use("/profile", profileRouter);
router.use("/meetings", meetingsRouter);
router.use("/chat", chatRouter);
router.use("/modules", modulesRouter);
router.use("/dev", devRouter);
router.use("/calendar", calendarRouter);
router.use("/", notificationSummaryRouter);
router.use("/rules", rulesRouter);

export default router;
